
export default function Home() {
  // Clases de css no implementadas TODO @Al
  return (
    <div className="contenedorHome">
      <h1>Cat ipsum</h1>
      <div className="bodyHome">
        Cat ipsum dolor sit amet, climb into cupboard and lick the salt off rice cakes please let me outside pouty face yay! wait, it's cold out please let me inside pouty face oh, thank you rub against mommy's leg oh it looks so nice out, please let me outside again the neighbor cat was mean to me please let me back inside and just going to dip my paw in your coffee and do a taste test - oh never mind i forgot i don't like coffee - you can have that back now. Scream for no reason at 4 am purrrrrr, ask to be pet then attack owners hand cats secretly make all the worlds muffins so put butt in owner's face scratch at fleas, meow until belly rubs, hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners food. Poop on floor and watch human clean up scratch leg; meow for can opener to feed me so my cat stared at me he was sipping his tea, too destroy house in 5 seconds and cry louder at reflection. Lounge in doorway steal raw zucchini off kitchen counter and playing with balls of wool. Give me attention or face the wrath of my claws making bread on the bathrobe and small kitty warm kitty little balls of fur peer out window, chatter at birds, lure them to mouth put butt in owner's face your pillow is now my pet bed for attack dog, run away and pretend to be victim. Why can't i catch that stupid red dot. Refuse to drink water except out of someone's glass love and coo around boyfriend who purrs and makes the perfect moonlight eyes so i can purr and swat the glittery gleaming yarn to him (the yarn is from a $125 sweater) sit as close as possible to warm fire without sitting on cold floor but flex claws on the human's belly and purr like a lawnmower. Eat the rubberband. Catty ipsum. Purr. Poop on grasses pet me pet me don't pet me and lick plastic bags yet climb into cupboard and lick the salt off rice cakes flop over. Eat fish on floor. Going to catch the red dot today going to catch the red dot today purrr purr littel cat, little cat purr purr. Lasers are tiny mice only use one corner of the litter box.
      </div>
    </div>
  )
}